gap_ind <- c("disasters", "gghed", "stunted", "wasted", "overweight", "mmr", "sba", "u5mr", "nmr", "hiv", "tb", "malaria", "hep_b", "ntd", 
         "ncd", "suicide", "substance", "alcohol", "traffic", "famplan", "adolescent", "uhc", "cat_10", "cat_25", "indoor", "ambient", 
         "wash", "poison", "tobacco", "dtp3", "mcv2", "pcv3", "assist", "medicines", "doctors", "nurses", "dentists", "pharmacists", 
         "ihr", "devontrack", "femviolence", "sexual_violence", "informed", "reprod_access", "water", "sanitation", "handwash", 
         "wastewater", "watsan_assist", "hhenergy", "fatal_t_b", "nfatal_t_b", "pm25", "homicide", "conflict_deaths", "violence", 
         "safe_walking", "childviolence", "sxvln_f", "sxvln_m", "reg_birth", "reg_census", "reg_births_90", "reg_deaths_75", 
         "services_vulnerable", "vaccines_atrisk", "amr_bloodstream", "amr_antibiotics", "num_polio", "hypertension", "transfats", "obese_5_19", "obese_adult")

# Objects to map indicator names to columns
gap_choices <- c("1.5.1 Natural disasters" = "disasters",
                 "1.a.2 Public health spending" = "gghed",
                 "2.2.1 Stunting under five" = "stunted",
                 "2.2.2 Wasting under five" = "wasted",
                 "2.2.2 Overweight under five" = "overweight",
                 "3.1.1 Maternal mortality" = "mmr",
                 "3.1.2 Skilled birth attendance" = "sba",
                 "3.2.1 Under 5 mortality" = "u5mr",
                 "3.2.2 Neonatal mortality" = "nmr",
                 "3.3.1 HIV incidence" = "hiv",
                 "3.3.2 TB incidence" = "tb",
                 "3.3.3 Malaria incidence" = "malaria",
                 "3.3.4 Hepatitis B incidence" = "hep_b",
                 "3.3.5 NTD numbers" = "ntd",
                 "3.4.1 NCD mortality" = "ncd",
                 "3.4.2 Suicide mortality" = "suicide",
                 "3.5.1 Substance use disorders" = "substance",
                 "3.5.2 Alcohol consumption" = "alcohol",
                 "3.6.1 Road traffic deaths" = "traffic",
                 "3.7.1 Family planning" = "famplan",
                 "3.7.2 Adolescent births" = "adolescent",
                 "3.8.1 UHC service coverage" = "uhc",
                 "3.8.2 Financial protection: 10%" = "cat_10",
                 "3.8.2 Financial protection: 25%" = "cat_25",
                 "3.9.1 Household pollution" = "indoor",
                 "3.9.1 Ambient air pollution" = "ambient",
                 "3.9.2 WASH related mortality" = "wash",
                 "3.9.3 Unintentional poisoning" = "poison",
                 "3.a.1 Tobacco use prevalence" = "tobacco",
                 "3.b.1 DTP3 coverage" = "dtp3",
                 "3.b.1 MCV2 coverage" = "mcv2",
                 "3.b.1 PCV3 coverage" = "pcv3",
                 "3.b.2 Development assistance" = "assist",
                 "3.b.3 Essential medicines" = "medicines",
                 "3.c.1 Doctors density" = "doctors",
                 "3.c.1 Nurses density" = "nurses",
                 "3.c.1 Dentists density" = "dentists",
                 "3.c.1 Pharmacists density" = "pharmacists",
                 "3.d.1 IHR" = "ihr",
                 "4.2.1 Child development" = "devontrack",
                 "5.2.1 Violence against women: partner" = "femviolence",
                 "5.2.2 Violence against women: other" = "sexual_violence",
                 "5.6.1 Informed decisions" = "informed",
                 "5.6.2 Reproductive health laws" = "reprod_access",
                 "6.1.1 Safe drinking water" = "water",
                 "6.2.1 Safe sanitation" = "sanitation",
                 "6.2.1 Handwashing facilities" = "handwash",
                 "6.3.1 Wastewater treatment" = "wastewater",
                 "6.a.1 ODA for watsan" = "watsan_assist",
                 "7.1.2 Clean fuels access" = "hhenergy",
                 "8.8.1 Fatal work injuries" = "fatal_t_b",
                 "8.8.1 Non-fatal work injuries" = "nfatal_t_b",
                 "11.6.2 PM2.5 concentration" = "pm25",
                 "16.1.1 Homicide rate" = "homicide",
                 "16.1.2 Conflict-related deaths" = "conflict_deaths",
                 "16.1.3 Prevalence of violence" = "violence",
                 "16.1.4 Safe walking areas" = "safe_walking",
                 "16.2.1 Violence against children" = "childviolence",
                 "16.2.3 Sexual violence: female" = "sxvln_f",
                 "16.2.3 Sexual violence: male" = "sxvln_m",
                 "16.9.1 Birth registration" = "reg_birth",
                 "17.19.2 Housing census (last 10 years)" = "reg_census", 
                 "17.19.2 100% birth registration" = "reg_births_90",
                 "17.19.2 80% death registration" = "reg_deaths_75",
                 "Access in fragile settings" = "services_vulnerable",
                 "Vaccines for at-risk population" = "vaccines_atrisk",
                 "AMR Bloodstream infections" = "amr_bloodstream",
                 "Access to antibiotics" = "amr_antibiotics",
                 "Number of Polio cases" = "num_polio",
                 "Hypertension prevalence" = "hypertension",
                 "Regulation on transfats" = "transfats",
                 "Obesity 5-19 years" = "obese_5_19",
                 "Obesity adult" = "obese_adult"
                 )

gap_column_names <- c("1.5.1 Natural disasters",
                  "1.a.2 Public health spending",
                  "2.2.1 Stunting under five",
                  "2.2.2 Wasting under five",
                  "2.2.2 Overweight under five",
                  "3.1.1 Maternal mortality",
                  "3.1.2 Skilled birth attendance",
                  "3.2.1 Under 5 mortality",
                  "3.2.2 Neonatal mortality",
                  "3.3.1 HIV incidence",
                  "3.3.2 TB incidence",
                  "3.3.3 Malaria incidence",
                  "3.3.4 Hepatitis B incidence",
                  "3.3.5 NTD numbers",
                  "3.4.1 NCD mortality",
                  "3.4.2 Suicide mortality",
                  "3.5.1 Substance use disorders",
                  "3.5.2 Alcohol consumption",
                  "3.6.1 Road traffic deaths",
                  "3.7.1 Family planning",
                  "3.7.2 Adolescent births",
                  "3.8.1 UHC service coverage",
                  "3.8.2 Financial protection: 10%",
                  "3.8.2 Financial protection: 25%",
                  "3.9.1 Household pollution",
                  "3.9.1 Ambient air pollution",
                  "3.9.2 WASH related mortality",
                  "3.9.3 Unintentional poisoning",
                  "3.a.1 Tobacco use prevalence",
                  "3.b.1 DTP3 coverage",
                  "3.b.1 MCV2 coverage",
                  "3.b.1 PCV3 coverage",
                  "3.b.2 Development assistance",
                  "3.b.3 Essential medicines",
                  "3.c.1 Doctors density",
                  "3.c.1 Nurses density",
                  "3.c.1 Dentists density",
                  "3.c.1 Pharmacists density",
                  "3.d.1 IHR",
                  "4.2.1 Child development",
                  "5.2.1 Violence against women: partner",
                  "5.2.2 Violence against women: other",
                  "5.6.1 Informed decisions",
                  "5.6.2 Reproductive health laws",
                  "6.1.1 Safe drinking water",
                  "6.2.1 Safe sanitation",
                  "6.2.1 Handwashing facilities",
                  "6.3.1 Wastewater treatment",
                  "6.a.1 ODA for watsan",
                  "7.1.2 Clean fuels access",
                  "8.8.1 Fatal work injuries",
                  "8.8.1 Non-fatal work injuries",
                  "11.6.2 PM2.5 concentration",
                  "16.1.1 Homicide rate",
                  "16.1.2 Conflict-related deaths",
                  "16.1.3 Prevalence of violence",
                  "16.1.4 Safe walking areas",
                  "16.2.1 Violence against children",
                  "16.2.3 Sexual violence: female",
                  "16.2.3 Sexual violence: male",
                  "16.9.1 Birth registration",
                  "17.19.2 Housing census (last 10 years)", 
                  "17.19.2 100% birth registration",
                  "17.19.2 80% death registration",
                  "Access in fragile settings",
                  "Vaccines for at-risk population",
                  "AMR Bloodstream infections",
                  "Access to antibiotics",
                  "Number of Polio cases",
                  "Hypertension prevalence",
                  "Regulation on transfats",
                  "Obesity 5-19 years",
                  "Obesity adult"
                   )

nonsdgs <- c("transfats", "obese_5_19", "obese_adult", "num_polio", "hypertension", "services_vulnerable",
             "vaccines_atrisk", "amr_bloodstream", "amr_antibiotics")

ind_label <- function(ind) {
  switch(ind,
         "disasters" = "Number of deaths attributed to disasters per 100 000 population",
         "gghed" = "Government health spending as proportion of total government spending",
         "stunted" ="Prevalence of stunting among children under 5 years of age",
         "wasted" = "Prevalence of wasting among children under 5 years of age",
         "overweight" = "Prevalence of overweight among children under 5 years of age",
         "mmr" = "Maternal mortality ratio per 100 000 live births",
         "sba" = "Proportion of births attended by skilled health personnel",
         "u5mr" = "Under-5 mortality rate per 1 000 live births",
         "nmr" = "Neonatal mortality rate per 1 000 live births",
         "hiv" = "Number of new HIV infections per 1 000 uninfected population",
         "tb" = "Tuberculosis incidence per 100 000 population",
         "malaria" = "Malaria incidence per 1 000 population",
         "hep_b" = "Hepatitis B incidence per 100 000 population",
         "ntd" = "Number of people requiring interventions against neglected tropical diseases",
         "ncd" = "Mortality rate attributed to cardiovascular disease, cancer, diabetes or chronic respiratory disease",
         "suicide" = "Suicide mortality rate",
         "substance" = "Coverage of treatment interventions for substance use disorders",
         "alcohol" = "Alcohol per capita consumption (15+ years) within a calendar year in litres of pure alcohol",
         "traffic" = "Death rate due to road traffic injuries",
         "famplan" = "Proportion of women (15 to 49 years) who have family planning needs satisfied with modern methods",
         "adolescent" = "Adolescent birth rate (15 to 19 years) per 100 000 women in that age group",
         "uhc" = "Coverage of essential health services",
         "cat_10" = "Proportion of population with hh health expenditures as a share of total hh expenditure or income > 10%",
         "cat_25" = "Proportion of population with hh health expenditures as a share of total hh expenditure or income > 25%",
         "indoor" = "Mortality rate attributed to household pollution",
         "ambient" = "Mortality rate attributed to ambient air pollution",
         "wash" = "Mortality rate attributed to unsafe water, unsafe sanitation and lack of hygiene",
         "poison" = "Mortality rate attributed to unintentional poisoning",
         "tobacco" = "Age-standardized prevalence of current tobacco use among persons aged 15 years and older",
         "dtp3" = "Proportion of the target population covered by DTP3 vaccinations",
         "mcv2" = "Proportion of the target population covered by MCV2 vaccinations",
         "pcv3" = "Proportion of the target population covered by PCV3 vaccinations",
         "assist" = "Total net official development assistance to medical research and basic health sectors",
         "medicines" = "Proportion of health facilities that have a core set of relevant essential medicines available",
         "doctors" = "Density of doctors per 10 000 population",
         "nurses" = "Density of nurses per 10 000 population",
         "dentists" = "Density of dentists per 10 000 population",
         "pharmacists" = "Density of pharmacists per 10 000 population",
         "ihr" = "International Health Regulations (IHR) capacity and health emergency preparedness",
         "devontrack" = "Proportion of children under 5 developmentally on track in health, learning and psychosocial well-being",
         "femviolence" = "Proportion of ever-partnered women aged 15-49 years subjected to intimate partner violence",
         "sexual_violence" = "Proportion of women aged 15+ years subjected to sexual violence by not an intimate partner",
         "informed" = "Proportion of women aged 15–49 years who make informed decisions on sexual and reproductive health",
         "reprod_access" = "Number of countries with laws that guarantee equal access on sexual and reproductive health care",
         "water" = "Proportion of population using safely managed drinking water services",
         "sanitation" = "Proportion of population using safely managed sanitation services",
         "handwash" = "Proportion of population using a handwashing facility with soap and water",
         "wastewater" = "Proportion of wastewater safely treated",
         "watsan_assist" = "Water and sanitation-related ODA that is part of a government-coordinated spending plan",
         "hhenergy" = "Proportion of population with primary reliance on clean fuels and technology",
         "fatal_t_b" = "Frequency rates of fatal occupational injuries",
         "nfatal_t_b" = "Frequency rates of non-fatal occupational injuries",
         "pm25" = "Annual mean levels of fine particulate matter (PM2.5) in cities",
         "homicide" = "Number of victims of intentional homicide per 100 000 population",
         "conflict_deaths" = "Conflict-related deaths per 100,000 population, by sex, age and cause",
         "violence" = "Proportion of population subjected to violence in the previous 12 months",
         "safe_walking" = "Proportion of population that feel safe walking alone around the area they live",
         "childviolence" = "Proportion of children aged 1-14 years who experienced physical/psychological aggression by caregivers",
         "sxvln_f" = "Proportion of young women aged 18–29 years who experienced sexual violence by age 18",
         "sxvln_m" = "Proportion of young men aged 18–29 years who experienced sexual violence by age 18",
         "reg_birth" = "Proportion of children under 5 years whose births have been registered with a civil authority",
         "reg_census" = "Proportion of countries that have conducted at least one population and housing census in last 10 years", 
         "reg_births_90" = "Proportion of countries that have achieved 100 per cent birth registration",
         "reg_deaths_75" = "Proportion of countries that have achieved 80 per cent death registration",
         "services_vulnerable" = "Proportion of vulnerable people in fragile settings provided with essential health services",
         "vaccines_atrisk" = "Vaccine coverage of at-risk groups for epidemic or pandemic prone diseases",
         "amr_bloodstream" = "Percentage of bloodstream infections due to antimicrobial resistant organisms",
         "amr_antibiotics" = "Patterns of antibiotic consumption at national level",
         "num_polio" = "Number of cases of poliomyelitis caused by wild poliovirus (WPV)",
         "hypertension" = "Age-standardized prevalence of raised blood pressure among 18+ years",
         "transfats" = "Percentage of people protected by effective regulation on trans fats",
         "obese_5_19" = "Prevalence of obesity among 5-19 years",
         "obese_adult" = "Prevalence of obesity among adults"
  )
}

gap_choices_full <- c(
  "Number of deaths attributed to disasters per 100 000 population" = "disasters",
  "Government health spending as proportion of total government spending" = "gghed",
  "Prevalence of stunting among children under 5 years of age" = "stunted",
  "Prevalence of wasting among children under 5 years of age" = "wasted",
  "Prevalence of overweight among children under 5 years of age" = "overweight",
  "Maternal mortality ratio per 100 000 live births" = "mmr",
  "Proportion of births attended by skilled health personnel" = "sba",
  "Under-5 mortality rate per 1 000 live births" = "u5mr",
  "Neonatal mortality rate per 1 000 live births" = "nmr",
  "Number of new HIV infections per 1 000 uninfected population" = "hiv",
  "Tuberculosis incidence per 100 000 population" = "tb",
  "Malaria incidence per 1 000 population" = "malaria",
  "Hepatitis B incidence per 100 000 population" = "hep_b",
  "Number of people requiring interventions against neglected tropical diseases" = "ntd",
  "Mortality rate attributed to cardiovascular disease, cancer, diabetes or chronic respiratory disease" = "ncd",
  "Suicide mortality rate" = "suicide",
  "Coverage of treatment interventions for substance use disorders" = "substance",
  "Alcohol per capita consumption (15+ years) within a calendar year in litres of pure alcohol" = "alcohol",
  "Death rate due to road traffic injuries" = "traffic",
  "Proportion of women (15 to 49 years) who have family planning needs satisfied with modern methods" = "famplan",
  "Adolescent birth rate (15 to 19 years) per 100 000 women in that age group" = "adolescent",
  "Coverage of essential health services" = "uhc",
  "Proportion of population with hh health expenditures as a share of total hh expenditure or income > 10%" = "cat_10",
  "Proportion of population with hh health expenditures as a share of total hh expenditure or income > 25%" = "cat_25",
  "Mortality rate attributed to household pollution" = "indoor",
  "Mortality rate attributed to ambient air pollution" = "ambient",
  "Mortality rate attributed to unsafe water, unsafe sanitation and lack of hygiene" = "wash",
  "Mortality rate attributed to unintentional poisoning" = "poison",
  "Age-standardized prevalence of current tobacco use among persons aged 15 years and older" = "tobacco",
  "Proportion of the target population covered by DTP3 vaccinations" = "dtp3",
  "Proportion of the target population covered by MCV2 vaccinations" = "mcv2",
  "Proportion of the target population covered by PCV3 vaccinations" = "pcv3",
  "Total net official development assistance to medical research and basic health sectors" = "assist",
  "Proportion of health facilities that have a core set of relevant essential medicines available" = "medicines",
  "Density of doctors per 10 000 population" = "doctors",
  "Density of nurses per 10 000 population" = "nurses",
  "Density of dentists per 10 000 population" = "dentists",
  "Density of pharmacists per 10 000 population" = "pharmacists",
  "International Health Regulations (IHR) capacity and health emergency preparedness" = "ihr",
  "Proportion of children under 5 developmentally on track in health, learning and psychosocial well-being" = "devontrack",
  "Proportion of ever-partnered women aged 15-49 years subjected to intimate partner violence" = "femviolence",
  "Proportion of women aged 15+ years subjected to sexual violence by not an intimate partner" = "sexual_violence",
  "Proportion of women aged 15–49 years who make informed decisions on sexual and reproductive health" = "informed",
  "Number of countries with laws that guarantee equal access on sexual and reproductive health care" = "reprod_access",
  "Proportion of population using safely managed drinking water services" = "water",
  "Proportion of population using safely managed sanitation services" = "sanitation",
  "Proportion of population using a handwashing facility with soap and water" = "handwash",
  "Proportion of wastewater safely treated" = "wastewater",
  "Water and sanitation-related ODA that is part of a government-coordinated spending plan" = "watsan_assist",
  "Proportion of population with primary reliance on clean fuels and technology" = "hhenergy",
  "Frequency rates of fatal occupational injuries" = "fatal_t_b",
  "Frequency rates of non-fatal occupational injuries" = "nfatal_t_b",
  "Annual mean levels of fine particulate matter (PM2.5) in cities" = "pm25",
  "Number of victims of intentional homicide per 100 000 population" = "homicide",
  "Conflict-related deaths per 100,000 population, by sex, age and cause" = "conflict_deaths",
  "Proportion of population subjected to violence in the previous 12 months" = "violence",
  "Proportion of population that feel safe walking alone around the area they live" = "safe_walking",
  "Proportion of children aged 1-14 years who experienced physical/psychological aggression by caregivers" = "childviolence",
  "Proportion of young women aged 18–29 years who experienced sexual violence by age 18" = "sxvln_f",
  "Proportion of young men aged 18–29 years who experienced sexual violence by age 18" = "sxvln_m",
  "Proportion of children under 5 years whose births have been registered with a civil authority" = "reg_birth",
  "Proportion of countries that have conducted at least one population and housing census in last 10 years" = "reg_census", 
  "Proportion of countries that have achieved 100 per cent birth registration" = "reg_births_90",
  "Proportion of countries that have achieved 80 per cent death registration" = "reg_deaths_75",
  "Proportion of vulnerable people in fragile settings provided with essential health services" = "services_vulnerable",
  "Vaccine coverage of at-risk groups for epidemic or pandemic prone diseases" = "vaccines_atrisk",
  "Number of cases of poliomyelitis caused by wild poliovirus (WPV)" = "num_polio",
  "Percentage of bloodstream infections due to antimicrobial resistant organisms" = "amr_bloodstream",
  "Patterns of antibiotic consumption at national level" = "amr_antibiotics",
  "Age-standardized prevalence of raised blood pressure among 18+ years" = "hypertension",
  "Percentage of people protected by effective regulation on trans fats" = "transfats",
  "Prevalence of obesity among 5-19 years" = "obese_5_19",
  "Prevalence of obesity among adults" = "obese_adult"
)

gap_colnames <- c(
  "Number of deaths attributed to disasters per 100 000 population",
  "Government health spending as proportion of total government spending",
  "Prevalence of stunting among children under 5 years of age",
  "Prevalence of wasting among children under 5 years of age",
  "Prevalence of overweight among children under 5 years of age",
  "Maternal mortality ratio per 100 000 live births",
  "Proportion of births attended by skilled health personnel",
  "Under-5 mortality rate per 1 000 live births",
  "Neonatal mortality rate per 1 000 live births",
  "Number of new HIV infections per 1 000 uninfected population",
  "Tuberculosis incidence per 100 000 population",
  "Malaria incidence per 1 000 population",
  "Hepatitis B incidence per 100 000 population",
  "Number of people requiring interventions against neglected tropical diseases",
  "Mortality rate attributed to cardiovascular disease, cancer, diabetes or chronic respiratory disease",
  "Suicide mortality rate",
  "Coverage of treatment interventions for substance use disorders",
  "Alcohol per capita consumption (15+ years) within a calendar year in litres of pure alcohol",
  "Death rate due to road traffic injuries",
  "Proportion of women (15 to 49 years) who have family planning needs satisfied with modern methods",
  "Adolescent birth rate (15 to 19 years) per 100 000 women in that age group",
  "Coverage of essential health services",
  "Proportion of population with hh health expenditures as a share of total hh expenditure or income > 10%",
  "Proportion of population with hh health expenditures as a share of total hh expenditure or income > 25%",
  "Mortality rate attributed to household pollution",
  "Mortality rate attributed to ambient air pollution",
  "Mortality rate attributed to unsafe water, unsafe sanitation and lack of hygiene",
  "Mortality rate attributed to unintentional poisoning",
  "Age-standardized prevalence of current tobacco use among persons aged 15 years and older",
  "Proportion of the target population covered by DTP3 vaccinations",
  "Proportion of the target population covered by MCV2 vaccinations",
  "Proportion of the target population covered by PCV3 vaccinations",
  "Total net official development assistance to medical research and basic health sectors",
  "Proportion of health facilities that have a core set of relevant essential medicines available",
  "Density of doctors per 10 000 population",
  "Density of nurses per 10 000 population",
  "Density of dentists per 10 000 population",
  "Density of pharmacists per 10 000 population",
  "International Health Regulations (IHR) capacity and health emergency preparedness",
  "Proportion of children under 5 developmentally on track in health, learning and psychosocial well-being",
  "Proportion of ever-partnered women aged 15-49 years subjected to intimate partner violence",
  "Proportion of women aged 15+ years subjected to sexual violence by not an intimate partner",
  "Proportion of women aged 15–49 years who make informed decisions on sexual and reproductive health",
  "Number of countries with laws that guarantee equal access on sexual and reproductive health care",
  "Proportion of population using safely managed drinking water services",
  "Proportion of population using safely managed sanitation services",
  "Proportion of population using a handwashing facility with soap and water",
  "Proportion of wastewater safely treated",
  "Water and sanitation-related ODA that is part of a government-coordinated spending plan",
  "Proportion of population with primary reliance on clean fuels and technology",
  "Frequency rates of fatal occupational injuries",
  "Frequency rates of non-fatal occupational injuries",
  "Annual mean levels of fine particulate matter (PM2.5) in cities",
  "Number of victims of intentional homicide per 100 000 population",
  "Conflict-related deaths per 100,000 population, by sex, age and cause",
  "Proportion of population subjected to violence in the previous 12 months",
  "Proportion of population that feel safe walking alone around the area they live",
  "Proportion of children aged 1-14 years who experienced physical/psychological aggression by caregivers",
  "Proportion of young women aged 18–29 years who experienced sexual violence by age 18",
  "Proportion of young men aged 18–29 years who experienced sexual violence by age 18",
  "Proportion of children under 5 years whose births have been registered with a civil authority",
  "Proportion of countries that have conducted at least one population and housing census in last 10 years", 
  "Proportion of countries that have achieved 100 per cent birth registration",
  "Proportion of countries that have achieved 80 per cent death registration",
  "Proportion of vulnerable people in fragile settings provided with essential health services",
  "Vaccine coverage of at-risk groups for epidemic or pandemic prone diseases",
  "Number of cases of poliomyelitis caused by wild poliovirus (WPV)",
  "Percentage of bloodstream infections due to antimicrobial resistant organisms",
  "Patterns of antibiotic consumption at national level",
  "Age-standardized prevalence of raised blood pressure among 18+ years",
  "Percentage of people protected by effective regulation on trans fats",
  "Prevalence of obesity among 5-19 years",
  "Prevalence of obesity among adults"
)
